### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [GNaive/naive-rete#24]
Hi: what would be the license for this repo?
Thanks!

**Comment by cmaclell** [comment]
I also would like to know the license. Thanks!

**Comment by pombredanne** [comment]
@dbbbit gentle ping?

**Comment by dbbbit** [comment]
just updated，it's MIT

**Comment by cmaclell** [comment]
Perfect, thanks!

**Comment by pombredanne** [comment]
@dbbbit Thank you for taking the time!

**Comment by pombredanne** [comment]
For reference this is the commit https://github.com/GNaive/naive-rete/commit/2bb0652a8026c6fc090b34c56b0325719973f16d
